#!/bin/bash -i

cargo build --release --target wasm32-unknown-unknown

wasm-bindgen \
  --out-dir ../../priv/static/assets/ \
  --target web target/wasm32-unknown-unknown/release/rust.wasm

cp ./index.html ../../priv/static/assets/
cp -r ./assets/ ../../priv/static/assets/
# cp -r ./js/ ../../priv/static/assets/